name: Publish on TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    enviroments:
      name: TestPyPI
      url: https://test.pypi.org/project/tw_invoice/${{ inputs.version }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit

      - name: Write version file
        run: |
          echo "__version__ = '${{ inputs.version }}'" >> tw_invoice/__init__.py

      - name: Commit version file
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions

      - name: Publish package
        env:
          FLIT_INDEX_URL: ${{ secrets.FLIT_INDEX_URL }}
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          flit publish
