name: Publish Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    enviroments: PyPI
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
      - name: Build package
        run: flit build
      - name: Publish package
        env:
          FLIT_INDEX_URL: ${{ secrets.FLIT_INDEX_URL }}
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          flit publish
