name: Test and Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
          flit install --deps develop --symlink
      - name: Test with pytest
        run: |
          pytest

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
          flit install --deps develop --symlink
      - name: Lint with flake8
        run: |
          flake8

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    environment: TestPyPI
    needs: [test, style]
    if: |
      always() && (github.event_name != 'pull_request') &&
      (needs.test.result == 'success') && (needs.style.result == 'success')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip flit
      - name: Build package
        run: flit build
      - name: Publish package
        env:
          FLIT_INDEX_URL: ${{ secrets.FLIT_INDEX_URL }}
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: |
          flit publish
